### ISSUE TITLE
Enhancement - check whether the IP address is being throttled

### ISSUE THREAD

**Issue by tautology0** [dievus/Oh365UserFinder#2]
The results may get throttled - in that case you'll be returned with false positives (i.e. it always returns "IfExistsResults":0). You can check throttle by looking whether "ThrottleStatus":1.

If would be nice to return a warning in this case.

**Comment by dievus** [comment]
Great idea. I'll get it added.

**Comment by dievus** [comment]
This is integrated. If you would like to do a pull and test it to let me know if you're getting the same success from the change as I am I would greatly appreciate it.

**Comment by tautology0** [comment]
Looks good to me! Thanks for the change!
